### ISSUE TITLE
Question about 3D environment data

### ISSUE THREAD

**Issue by many-bees** [laura-a-n-n/silent-hill-museum#9]
I was wondering how the data for 3D environments that aren't in the .mdl format are stored. Stuff like walls and streets and buildings. I found a way to extract the textures for those environments in 2 and 3 but I'm interested in how the games handle the 3D data for them. As far as I can tell the data is stored in either .map files, .cam files, .cld files, or .kg2 files. What are these file types for?

**Comment by many-bees** [comment]
Actually I have another question as well. The character models don't have any face bones aside from the jaw and eyes, so how are the faces animated in-game? The same thing is true of SH3 models so it can't just be FMVs.

**Comment by laura-a-n-n** [comment]
hi @many-bees !

yep, 3d environments are stored in map files -- i recommend checking out pmttavara's [ph2](https://github.com/pmttavara/ph2) for an absolutely amazing map viewer/editor :)

cld is collision data; checkout bigmanjapan's explanation [here](https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/101#issuecomment-475954703)

cam is for cutscenes, which my friend quaker has done some work on, but hasn't been fully reversed afaik?

kg2 is for map shadows, while kg1 is for character shadows. it has been reversed, see murugo's documentation [here](https://github.com/Polymega/SilentHillDatabase/blob/master/SH2/Files/kg.md) 

i plan on supporting maps in the museum soon, but haven't gotten there yet! i'm working hard to finish my model editor -- expect a big update next weekend!

> The character models don't have any face bones aside from the jaw and eyes, so how are the faces animated in-game? The same thing is true of SH3 models so it can't just be FMVs.

you're right! this is the purpose of the `cluster_nodes` section in the mdl files, which is blendshapes/morph targets. basically it just blends between different shapes to get different facial expressions. murugo has reversed this for ps2 (and pc, although he hasn't uploaded it to github): https://github.com/Murugo/Misc-Game-Research/blob/main/PS2/Silent%20Hill%202%2B3/Blender/addons/io_sh2_sh3/import_mdl.py
this is also planned to be ported over into the museum.

**Comment by many-bees** [comment]
Damn now I'm really excited

**Comment by many-bees** [comment]
When you say Murugo hasn't uploaded his reverse engineering of PC .mdl files but hasn't uploaded it to github, is there any place where he has uploaded it? And do you know of anyone who's working on the same for Silent Hill 4?
